AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Flask application deployed to AWS Lambda

Globals:
  Function:
    Timeout: 30
    Runtime: python3.10 # Adjust to your Python version
    Environment:
      Variables:
        DYNAMODB_TABLE: ReflectionsTable # DynamoDB table name

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/ReflectionsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
